# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shoppingtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_920c185d407f4deb9540573656acd231 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9972ff6697ce4de28f129fcf7e7c37e0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_920c185d407f4deb9540573656acd231 }}/naren45358 / shoppingclient:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shoppingtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d346a1a8b55648ef90d22c4007ed988a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_920c185d407f4deb9540573656acd231 }}/naren45358 / shoppingclient:${{ github.sha }}'